### ISSUE TITLE
a99SBdisp_water.gro vacuum?

### ISSUE THREAD

**Issue by sobuelow** [paulrobustelli/Force-Fields#1]
There is some empty space in the reference water a99SBdisp_water.gro structure file of the a99SBdisp FF. This empty space also translates into solvated simulation boxes. Is that intended?
Best,
Soeren

**Comment by nekitmm** [comment]
a99SBdisp_water.gro file is clearly bugged... There are random atoms around the box. There is a problem with coordinates of some sort.

**Comment by paulrobustelli** [comment]
It is not intended, and that file was included more as a reference for the naming conventions that are compatible with the FF distribution.   Perhaps you can use the atom naming conventions found in a99SBdisp_water.gro to generate a new waterbox template.
________________________________

**Comment by hgandhi2411** [comment]
@paulrobustelli the atom names in a99SBdisp_water.itp and a99SBdisp_water.gro are different. Which ones are the correct names for this forcefield?

**Comment by paulrobustelli** [comment]
default tip4p.gro should work for generating water boxes, though I updated a99SBdisp_water.gro so that it is 7.5nm box with the correct atom names without gaps.  

If you need to make a new water box with a different size:

Make a file called a99SBdisp_water.top:

*****a99SBdisp_water.top****
#include "a99SBdisp.ff/forcefield.itp"
#incldue "a99SBdisp.ff/a99SBdisp_water.itp"

[ System ]
A99SBDISP_WATER
******** 

gmx solvate -cs tip4p  -o a99SBdisp_water.gro -box 7.5 7.5 7.5 -p a99SBdisp_water.top
#rename HW2 > HW3, HW1 > HW2, MW > MW4 to make a99SBdisp_water.rename.gro 
sed 's/HW2/HW3/g' a99SBdisp_water.gro > rename1
sed 's/HW1/HW2/g' rename1 > rename2
sed 's/ MW/MW4/g' rename2 > a99SBdisp_water.gro
