### ISSUE TITLE
Scaled charges of 0.9 in des-amber and a99SB-disp

### ISSUE THREAD

**Issue by janmarzinek** [paulrobustelli/Force-Fields#4]

**Comment by paulrobustelli** [comment]
Which force fields files are you pointing towards? It seems like you might be using DES-amber, which has scaled charges (of 0.9) and not a99SB-disp.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: janmarzinek ***@***.***>
Sent: Tuesday, April 27, 2021 11:21:16 PM
To: paulrobustelli/Force-Fields ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [paulrobustelli/Force-Fields] Wrongly assigned charges in a99SB-disp GROMACS version? (#4)


Did a quick test using "gmx pdb2gmx" on my protein with overall -13 charge at neutral pH. The resulting charge using a99SB-disp is -11.7. The problem starts already with N-terminal, my MET overall charge is 0.9 rather than 1.0.
